### PR TITLE
feat: removing stray yaml dump

### PR DESCRIPTION
**Pull request by dmerrick**
### What changes were proposed in this pull request?

This fixes https://github.com/couler-proj/couler/issues/248

In that issue, @merlintang mentions this section can be removed.

### Why are the changes needed?

Since this code is not contained in a method, it ends up being called outside of the context of couler/argo.

### Does this PR introduce _any_ user-facing change?

Only the reduction of output.

### How was this patch tested?

Removed this and raised an exception and didn't get the yaml dump

### CODE REVIEW

**Comment by merlintang** [comment]
/lgtm

can we make this configurable, I am not sure whether other customers need to see the generated YAML for debugging?

**Comment by dmerrick** [comment]
When I debug I manually call `couler._dump_yaml()` and it works for me

**Comment by merlintang** [comment]
we can not merge on the web front end directly ? it is wired.

**Review by terrytangyuan — APPROVED** [review]

**Comment by terrytangyuan** [comment]
@merlintang You need to click the diff and then click approve explicitly before you can merge it.

**Comment by merlintang** [comment]
thanks terry. :)

**Pull request merged**
